// Onglet Outils, données du marché : les zones de chaque indicateur et ce qu'elles impliquent, en mots simples.
// Chaque zone : id, nom, plage (texte court), ce que ça veut dire, effet habituel sur le prix, comment s'en servir.
// L'outil calcule la zone du jour et, pour chaque zone, ce qu'a fait le prix ensuite (js/outils-data.js, afterStats).

// Zones par rang : la valeur du jour comparée à tout l'historique disponible.
export const rankZone = r => (r == null ? null : r < 15 ? 'bas' : r > 85 ? 'haut' : 'normal');
const RANK = { bas: 'parmi les 15 % des jours les plus bas', normal: 'entre les deux', haut: 'parmi les 15 % des jours les plus hauts' };

export const ZONES = {
  longshort: [
    { id: 'bas', name: 'Très bas', range: RANK.bas,
      means: "Beaucoup plus de comptes que d'habitude parient sur la baisse.",
      price: 'Les vendeurs sont nombreux. Si le prix remonte, ils doivent racheter pour limiter leurs pertes, ce qui peut accélérer la hausse.',
      use: "Ce n'est pas un signal d'achat à lui seul. Il dit surtout que la foule a déjà joué la baisse : évite de vendre dans la panique et attends que la tendance se retourne pour acheter." },
    { id: 'normal', name: 'Habituel', range: RANK.normal,
      means: "Ni excès d'optimisme, ni excès de pessimisme.",
      price: "Pas d'effet particulier : c'est la tendance qui décide.",
      use: 'Ne décide pas avec cet indicateur. Regarde la tendance (onglet Marché) et les Setups.' },
    { id: 'haut', name: 'Très haut', range: RANK.haut,
      means: "Beaucoup plus de comptes que d'habitude parient sur la hausse, souvent avec du levier.",
      price: "Si le prix baisse, ces acheteurs à levier sont forcés de vendre (liquidations), ce qui peut faire chuter le prix d'un coup. Le prix a souvent du mal à continuer à monter vite.",
      use: "Évite d'acheter en plein emballement. Si tu as déjà une position, garde un stop : c'est dans ces moments que les chutes brutales arrivent." },
  ],
  top: [
    { id: 'bas', name: 'Gros traders vendeurs', range: RANK.bas,
      means: "Les traders aux plus grosses positions ont beaucoup plus de shorts que d'habitude.",
      price: "De grosses sommes parient sur la baisse. Ils n'ont pas toujours raison, mais quand ils vont dans le sens de la tendance, la baisse a plus de chances de continuer.",
      use: "Prudence avant d'acheter. Si la foule (outil Long / short) est au même moment très acheteuse, c'est une raison de plus de se méfier." },
    { id: 'normal', name: 'Habituel', range: RANK.normal,
      means: "Les gros traders ne penchent pas plus que d'habitude d'un côté.",
      price: "Pas d'effet particulier.",
      use: "Regarde plutôt l'écart avec la foule : quand les gros et les petits font l'inverse les uns des autres, c'est plus parlant." },
    { id: 'haut', name: 'Gros traders acheteurs', range: RANK.haut,
      means: "Les traders aux plus grosses positions sont beaucoup plus acheteurs que d'habitude.",
      price: 'De gros montants misent sur la hausse. Si la foule est pessimiste au même moment, beaucoup de traders y voient un bon signe pour la hausse.',
      use: 'Plutôt rassurant pour un achat dans le sens de la tendance. Vérifie quand même la tendance avant d\'agir : les gros se trompent aussi.' },
  ],
  taker: [
    { id: 'bas', name: 'Vendeurs pressés', range: RANK.bas,
      means: "Cette semaine, ceux qui vendent tout de suite au prix du marché dominent plus que d'habitude.",
      price: "Pression à la baisse à court terme. Mais si le prix arrête de baisser malgré ces ventes, c'est que des acheteurs patients absorbent tout : souvent le signe qu'un point bas approche.",
      use: "N'achète pas tant que le prix continue de baisser. Guette le moment où il ne baisse plus alors que les ventes continuent." },
    { id: 'normal', name: 'Équilibre', range: RANK.normal,
      means: 'Achats pressés et ventes pressées se compensent à peu près.',
      price: "Pas d'effet particulier.",
      use: 'Regarde les autres indicateurs.' },
    { id: 'haut', name: 'Acheteurs pressés', range: RANK.haut,
      means: "Cette semaine, ceux qui achètent tout de suite, sans attendre un meilleur prix, dominent plus que d'habitude.",
      price: 'Pression à la hausse à court terme. Si le prix ne monte pas malgré ces achats, des vendeurs patients revendent tout : signe de faiblesse.',
      use: 'Bon signe si le prix monte avec. Méfiance si le prix stagne alors que les achats dominent.' },
  ],
  fng: [
    { id: 'pe', name: 'Peur extrême', range: '0 à 25',
      means: 'Le marché panique : fortes baisses, prix qui bouge beaucoup, réseaux sociaux très pessimistes.',
      price: "Beaucoup de traders y voient une occasion, car les points bas arrivent souvent dans la peur. Mais la panique peut durer des semaines et le prix peut encore baisser avant de repartir.",
      use: "Mauvais moment pour vendre sous le coup de la peur. Bon moment pour acheter petit à petit (DCA) si tu vises le long terme, pas pour tout miser d'un coup." },
    { id: 'p', name: 'Peur', range: '26 à 44',
      means: 'Le marché est inquiet.',
      price: "Pas un signal fort à lui seul : la peur peut précéder une baisse comme un rebond.",
      use: 'Reste sur ton plan, sans te laisser emporter par le pessimisme ambiant.' },
    { id: 'n', name: 'Neutre', range: '45 à 55',
      means: "Ni peur, ni euphorie.",
      price: "Pas d'effet particulier.",
      use: 'Regarde la tendance.' },
    { id: 'a', name: 'Avidité', range: '56 à 74',
      means: 'Le marché est confiant.',
      price: "Normal quand le marché monte : cette confiance peut durer des mois.",
      use: "Suis la tendance, mais n'augmente pas ton levier parce que tout le monde est confiant." },
    { id: 'ae', name: 'Avidité extrême', range: '75 à 100',
      means: 'Euphorie : presque tout le monde est confiant, souvent après une forte hausse.',
      price: "Les sommets arrivent souvent dans l'euphorie. En marché haussier, elle peut quand même durer, avec des replis brutaux plus fréquents.",
      use: "Évite d'entrer gros maintenant. Si tu as des gains, c'est le moment de remonter tes stops ou d'en encaisser une partie." },
  ],
  oi: [
    { id: 'up-up', name: 'Le levier monte avec le prix', range: 'contrats en hausse, prix en hausse',
      means: "De nouveaux contrats s'ouvrent pendant que le prix monte : de l'argent frais parie sur la hausse.",
      price: 'La hausse est soutenue, mais le levier s\'accumule : plus il est haut, plus une baisse peut être brutale (liquidations en chaîne).',
      use: 'Bon pour suivre une tendance haussière. Garde un stop, surtout si les contrats ouverts atteignent un record.' },
    { id: 'up-down', name: 'Le levier monte pendant la baisse', range: 'contrats en hausse, prix en baisse',
      means: "De nouveaux contrats s'ouvrent pendant que le prix baisse : des vendeurs à découvert (shorts) entrent.",
      price: 'Pression à la baisse. Mais si le prix se retourne, tous ces vendeurs devront racheter : la remontée peut être violente (squeeze).',
      use: "N'achète pas contre la baisse. Guette un retournement net du prix : c'est là que le squeeze démarre." },
    { id: 'down-up', name: 'Hausse sans argent frais', range: 'contrats en baisse, prix en hausse',
      means: 'Le prix monte alors que des contrats se ferment : ce sont surtout des vendeurs qui rachètent pour sortir.',
      price: "Hausse moins solide : elle peut s'essouffler si de nouveaux acheteurs ne prennent pas le relais.",
      use: "Méfiance avant d'acheter en haut. Attends de voir de l'argent frais arriver (contrats qui remontent avec le prix)." },
    { id: 'down-down', name: 'Nettoyage du levier', range: 'contrats en baisse, prix en baisse',
      means: 'Le prix baisse et des contrats se ferment : des acheteurs à levier sortent ou se font liquider.',
      price: "Ça arrive souvent en fin de vague de baisse : une fois le levier parti, le risque de chute en chaîne diminue.",
      use: "Pas forcément le moment d'acheter tout de suite, mais le pire de la vague est souvent passé." },
    { id: 'flat', name: 'Levier stable', range: 'contrats à moins de 5 % de variation',
      means: 'Le nombre de contrats ouverts bouge peu sur la semaine.',
      price: 'Pas d\'information particulière.',
      use: 'Regarde les autres indicateurs.' },
  ],
  funding: [
    { id: 'neg', name: 'Négatif', range: 'sous 0 %',
      means: 'Les vendeurs à découvert paient les acheteurs : la majorité du levier parie sur la baisse.',
      price: "Si le prix monte, ces vendeurs doivent racheter, ce qui peut accélérer la hausse (squeeze).",
      use: 'Pas le moment de vendre à découvert avec tout le monde. Un retournement à la hausse peut être brutal.' },
    { id: 'calme', name: 'Calme', range: '0 à 0,01 %',
      means: 'Peu de déséquilibre entre acheteurs et vendeurs à levier.',
      price: "Pas d'effet particulier : c'est la zone normale.",
      use: 'Rien à signaler, suis la tendance.' },
    { id: 'charge', name: 'Chargé en longs', range: '0,01 à 0,03 %',
      means: 'Les acheteurs à levier sont plus nombreux et paient pour garder leur position.',
      price: 'Normal en marché haussier. Plus ça dure, plus le marché est fragile en cas de mauvaise nouvelle.',
      use: 'Garde un stop sur tes positions acheteuses.' },
    { id: 'tres', name: 'Très chargé', range: 'au-dessus de 0,03 %',
      means: 'Beaucoup de traders achètent avec du levier et paient cher pour ça.',
      price: 'Une petite baisse peut déclencher des ventes forcées en chaîne (liquidations). Ces excès finissent souvent par une chute rapide.',
      use: "Évite d'acheter avec du levier maintenant. Si tu es déjà long, protège tes gains." },
  ],
  etf: [
    { id: 'bas', name: 'Grosses sorties', range: RANK.bas,
      means: "Beaucoup plus d'argent que d'habitude est sorti des ETF ces 5 derniers jours de bourse.",
      price: 'Les gros investisseurs vendent : ça pèse sur le prix. Ça arrive souvent pendant une baisse ou juste après.',
      use: "Prudence avant d'acheter tant que les sorties continuent." },
    { id: 'normal', name: 'Habituel', range: RANK.normal,
      means: 'Des entrées et des sorties dans la moyenne.',
      price: "Pas d'effet particulier.",
      use: 'Regarde plutôt les séries de plusieurs jours dans le même sens.' },
    { id: 'haut', name: 'Grosses entrées', range: RANK.haut,
      means: "Beaucoup plus d'argent que d'habitude est entré dans les ETF ces 5 derniers jours de bourse.",
      price: 'Les gros investisseurs achètent : ça soutient le prix, surtout quand ça dure plusieurs semaines. Mais ils achètent souvent après une hausse, pas avant.',
      use: 'Bon signe pour une tendance haussière. Une seule grosse semaine ne suffit pas : regarde si ça continue.' },
  ],
};

// Zone du Fear & Greed, avec les mêmes bornes que l'onglet Marché.
export const fngZone = v => (v <= 25 ? 'pe' : v < 45 ? 'p' : v <= 55 ? 'n' : v < 75 ? 'a' : 'ae');
// Zone du funding BTC (moyenne du jour, en % par 8 h).
export const fundingZone = v => (v < 0 ? 'neg' : v < 0.01 ? 'calme' : v < 0.03 ? 'charge' : 'tres');
// Zone de l'open interest : variation sur 7 jours des contrats ouverts et du prix, en %.
export const oiZone = (oiCh, priceCh) => (Math.abs(oiCh) < 5 ? 'flat' : `${oiCh > 0 ? 'up' : 'down'}-${priceCh >= 0 ? 'up' : 'down'}`);
